### ISSUE TITLE
[Enhancement]: Set path to access

### ISSUE THREAD

**Issue by ljrodriguez1** [AzouKr/sqlite-gui-node#3]
I would love to use this project, but i need to access the gui on the same port that the express server is exposed.

Is there a way of doing this, setting in wich path would i access the service

**Comment by AzouKr** [comment]
I guess it is possible, i will work on this in the next couple days, it will be like a middleware for express js.

**Comment by AzouKr** [comment]
@ljrodriguez1  You can check now the new documentation about how to use it as middleware and test it and give me feedbacks

**Comment by AzouKr** [comment]
Now you can use the GUI as same port as Express
